### ISSUE TITLE
nixfromnpm is compiled multiple times during build

### ISSUE THREAD

**Issue by adnelson** [adnelson/nixfromnpm#105] opened 2018-02-18 19:02 UTC
Presumably due to the way the cabal file is built, `nixfromnpm` code is compiled several times, resulting in unnecessarily long build times.

```
building
Building nixfromnpm-0.13.0...
Preprocessing library nixfromnpm-0.13.0...
[ 1 of 13] Compiling Paths_nixfromnpm ( dist/build/autogen/Paths_nixfromnpm.hs, dist/build/Paths_nixfromnpm.o )
[ 2 of 13] Compiling Filesystem.Path.Wrappers ( src/Filesystem/Path/Wrappers.hs, dist/build/Filesystem/Path/Wrappers.o )
[ 3 of 13] Compiling NixFromNpm.Common ( src/NixFromNpm/Common.hs, dist/build/NixFromNpm/Common.o )
[ 4 of 13] Compiling NixFromNpm.Git.Types ( src/NixFromNpm/Git/Types.hs, dist/build/NixFromNpm/Git/Types.o )
[ 5 of 13] Compiling NixFromNpm.HttpTools ( src/NixFromNpm/HttpTools.hs, dist/build/NixFromNpm/HttpTools.o )
[ 6 of 13] Compiling NixFromNpm.Npm.PackageMap ( src/NixFromNpm/Npm/PackageMap.hs, dist/build/NixFromNpm/Npm/PackageMap.o )
[ 7 of 13] Compiling NixFromNpm.Npm.Version ( src/NixFromNpm/Npm/Version.hs, dist/build/NixFromNpm/Npm/Version.o )
[ 8 of 13] Compiling NixFromNpm.Npm.Types ( src/NixFromNpm/Npm/Types.hs, dist/build/NixFromNpm/Npm/Types.o )
[ 9 of 13] Compiling NixFromNpm.Conversion.ToNix ( src/NixFromNpm/Conversion/ToNix.hs, dist/build/NixFromNpm/Conversion/ToNix.o )
[10 of 13] Compiling NixFromNpm.Npm.Resolve ( src/NixFromNpm/Npm/Resolve.hs, dist/build/NixFromNpm/Npm/Resolve.o )
[11 of 13] Compiling NixFromNpm.Options ( src/NixFromNpm/Options.hs, dist/build/NixFromNpm/Options.o )
[12 of 13] Compiling NixFromNpm.Conversion.ToDisk ( src/NixFromNpm/Conversion/ToDisk.hs, dist/build/NixFromNpm/Conversion/ToDisk.o )
[13 of 13] Compiling NixFromNpm       ( src/NixFromNpm.hs, dist/build/NixFromNpm.o )
Preprocessing executable 'nixfromnpm' for nixfromnpm-0.13.0...
[ 1 of 14] Compiling Paths_nixfromnpm ( dist/build/autogen/Paths_nixfromnpm.hs, dist/build/nixfromnpm/nixfromnpm-tmp/Paths_nixfromnpm.dyn_o )
[ 2 of 14] Compiling Filesystem.Path.Wrappers ( src/Filesystem/Path/Wrappers.hs, dist/build/nixfromnpm/nixfromnpm-tmp/Filesystem/Path/Wrappers.dyn_o )
[ 3 of 14] Compiling NixFromNpm.Common ( src/NixFromNpm/Common.hs, dist/build/nixfromnpm/nixfromnpm-tmp/NixFromNpm/Common.dyn_o )
[ 4 of 14] Compiling NixFromNpm.Git.Types ( src/NixFromNpm/Git/Types.hs, dist/build/nixfromnpm/nixfromnpm-tmp/NixFromNpm/Git/Types.dyn_o )
[ 5 of 14] Compiling NixFromNpm.HttpTools ( src/NixFromNpm/HttpTools.hs, dist/build/nixfromnpm/nixfromnpm-tmp/NixFromNpm/HttpTools.dyn_o )
[ 6 of 14] Compiling NixFromNpm.Npm.PackageMap ( src/NixFromNpm/Npm/PackageMap.hs, dist/build/nixfromnpm/nixfromnpm-tmp/NixFromNpm/Npm/PackageMap.dyn_o )
[ 7 of 14] Compiling NixFromNpm.Npm.Version ( src/NixFromNpm/Npm/Version.hs, dist/build/nixfromnpm/nixfromnpm-tmp/NixFromNpm/Npm/Version.dyn_o )
[ 8 of 14] Compiling NixFromNpm.Npm.Types ( src/NixFromNpm/Npm/Types.hs, dist/build/nixfromnpm/nixfromnpm-tmp/NixFromNpm/Npm/Types.dyn_o )
[ 9 of 14] Compiling NixFromNpm.Conversion.ToNix ( src/NixFromNpm/Conversion/ToNix.hs, dist/build/nixfromnpm/nixfromnpm-tmp/NixFromNpm/Conversion/ToNix.dyn_o )
[10 of 14] Compiling NixFromNpm.Npm.Resolve ( src/NixFromNpm/Npm/Resolve.hs, dist/build/nixfromnpm/nixfromnpm-tmp/NixFromNpm/Npm/Resolve.dyn_o )
[11 of 14] Compiling NixFromNpm.Options ( src/NixFromNpm/Options.hs, dist/build/nixfromnpm/nixfromnpm-tmp/NixFromNpm/Options.dyn_o )
[12 of 14] Compiling NixFromNpm.Conversion.ToDisk ( src/NixFromNpm/Conversion/ToDisk.hs, dist/build/nixfromnpm/nixfromnpm-tmp/NixFromNpm/Conversion/ToDisk.dyn_o )
[13 of 14] Compiling NixFromNpm.Merge ( src/NixFromNpm/Merge.hs, dist/build/nixfromnpm/nixfromnpm-tmp/NixFromNpm/Merge.dyn_o )
[14 of 14] Compiling Main             ( src/Main.hs, dist/build/nixfromnpm/nixfromnpm-tmp/Main.dyn_o )
Linking dist/build/nixfromnpm/nixfromnpm ...
Preprocessing test suite 'unit-tests' for nixfromnpm-0.13.0...
[ 1 of 14] Compiling Paths_nixfromnpm ( dist/build/autogen/Paths_nixfromnpm.hs, dist/build/unit-tests/unit-tests-tmp/Paths_nixfromnpm.dyn_o )
[ 2 of 14] Compiling Filesystem.Path.Wrappers ( src/Filesystem/Path/Wrappers.hs, dist/build/unit-tests/unit-tests-tmp/Filesystem/Path/Wrappers.dyn_o )
[ 3 of 14] Compiling NixFromNpm.Common ( src/NixFromNpm/Common.hs, dist/build/unit-tests/unit-tests-tmp/NixFromNpm/Common.dyn_o )
[ 4 of 14] Compiling NixFromNpm.Git.Types ( src/NixFromNpm/Git/Types.hs, dist/build/unit-tests/unit-tests-tmp/NixFromNpm/Git/Types.dyn_o )
[ 5 of 14] Compiling NixFromNpm.HttpTools ( src/NixFromNpm/HttpTools.hs, dist/build/unit-tests/unit-tests-tmp/NixFromNpm/HttpTools.dyn_o )
[ 6 of 14] Compiling NixFromNpm.Npm.PackageMap ( src/NixFromNpm/Npm/PackageMap.hs, dist/build/unit-tests/unit-tests-tmp/NixFromNpm/Npm/PackageMap.dyn_o )
[ 7 of 14] Compiling NixFromNpm.Npm.Version ( src/NixFromNpm/Npm/Version.hs, dist/build/unit-tests/unit-tests-tmp/NixFromNpm/Npm/Version.dyn_o )
[ 8 of 14] Compiling NixFromNpm.Npm.Types ( src/NixFromNpm/Npm/Types.hs, dist/build/unit-tests/unit-tests-tmp/NixFromNpm/Npm/Types.dyn_o )
[ 9 of 14] Compiling NixFromNpm.Conversion.ToNix ( src/NixFromNpm/Conversion/ToNix.hs, dist/build/unit-tests/unit-tests-tmp/NixFromNpm/Conversion/ToNix.dyn_o )
[10 of 14] Compiling NixFromNpm.Npm.Resolve ( src/NixFromNpm/Npm/Resolve.hs, dist/build/unit-tests/unit-tests-tmp/NixFromNpm/Npm/Resolve.dyn_o )
[11 of 14] Compiling NixFromNpm.Options ( src/NixFromNpm/Options.hs, dist/build/unit-tests/unit-tests-tmp/NixFromNpm/Options.dyn_o )
[12 of 14] Compiling NixFromNpm.Conversion.ToDisk ( src/NixFromNpm/Conversion/ToDisk.hs, dist/build/unit-tests/unit-tests-tmp/NixFromNpm/Conversion/ToDisk.dyn_o )
[13 of 14] Compiling NixFromNpm       ( src/NixFromNpm.hs, dist/build/unit-tests/unit-tests-tmp/NixFromNpm.dyn_o )
[14 of 14] Compiling Main             ( tests/Unit.hs, dist/build/unit-tests/unit-tests-tmp/Main.dyn_o )
Linking dist/build/unit-tests/unit-tests ...
running tests
Running 1 test suites...
```

Presumably this would just involve restructuring the cabal file, but I'm not sure the best way to do it.

**Comment by ixmatus** [comment] 2018-02-18 19:52
I think this ticket is technically a duplicate of #80 which documents the root cause of what this ticket describes.

The solution is to make `nixfromnpm` a library which is then also provided in the build-depends sections for the executable and test.

An example of doing this can be found in the `hocker` project. For instance we define a `library` section that contains the majority of the generic code: https://github.com/awakesecurity/hocker/blob/master/hocker.cabal#L47

Which is then depended on by the more specific executables: https://github.com/awakesecurity/hocker/blob/master/hocker.cabal#L122

If `nixfromnpm` were structured in a similar manner, it would fix this specific issue. I tried tackling that a long time ago but realized that in order to do this the refactoring is going to cut deep and in the interest of not submitting giant controversial pull requests I refrained from doing that.

However, I fully support doing this work because library-izing `nixfromnpm` can only be good because in the short-term it will make the code organization clearer but long-term it makes it easier to generalize this project to something that generates build instructions for other systems beyond Nix if someone else (or you!) wanted to do that.

**Comment by ixmatus** [comment] 2018-02-18 20:00
I think it would be less controversial at this point to do that refactoring work though.

However, if I were to prioritize this work, I'd say that it is actually less important than a few other refactoring needs which have a material impact on the usability of the resulting code generation product.

Notably, I think we need to make a backwards breaking refactor to the way that we import and call individual node packages so that they take all of their dependencies at the top-level of their intake arguments instead of in the `nodePackages` argument. The reason for this is that it impedes easy overriding of the dependencies that are threaded into the package.

I think solving the optionalDependencies issue is also more important and I think making the build and install steps more easily overridden are more important.

**Comment by adnelson** [comment] 2018-02-18 20:01
As an initial pass, I don't think it needs to be a large refactor -- the PR that I just made speeds up the build and thus solves at least the surface level problem. I agree it's not the most important issue, but having faster iteration times is pretty nice.

**Comment by ixmatus** [comment] 2018-02-18 20:10
Yeah for some reason when I tried doing that I think I started following the interface exports and it seemed hairier at the time than your existing PR makes it seem. Maybe I'm mis-remembering something. Either way good to see it was such a quick change!

I agree that faster iteration time is a good thing.

**Comment by adnelson** [comment] 2018-02-18 20:12
When I first tried it, I got a bunch of errors about missing symbols that looked super gnarly. I realized that was just because I wasn't listing the packages in the `other-modules` section. Which to me seems like a really basic piece of functionality missing from cabal, but that fixed that.

**Closed** 2018-02-18 20:14 UTC
