### ISSUE TITLE
A circular dependency is detected when there actually is none

### ISSUE THREAD

**Issue by ixmatus** [adnelson/nixfromnpm#103] opened 2018-02-17 03:36 UTC
The generated package for `webpack-3.11.0` had `uglifyjs-webpack-plugin_0-4-6` in its circular dependencies list (and `uglifyjs-webpack-plugin_0-4-6` had webpack in its _peer dependencies_) but the `circularClosure` function didn't find the cycle in the depset which means there isn't actually a circular dependency.

#102 addresses a nix-build failure due to this issue but the root cause is in the Haskell code that determines there is a circular dependency.

My intuition is telling me that it incorrectly detected circularity due to the peer dependency in `uglifyjs-webpack-plugin` on `webpack`.

**Comment by adnelson** [comment] 2018-02-19 19:14
So as it stands now, webpack depends (non-peer) on uglify, and uglify depends (peer) on webpack. To the extent that I understand peer dependencies, I believe the intention is to indicate that that version of uglify is meant to work alongside that version of webpack, but not necessarily that it depends on it in the normal sense. Maybe then the issue is not about the circularity, but about how peer dependencies are treated in general. `nixfromnpm` treats this as circular because it attempts to resolve the definitions of peer dependencies just as it would any other type of dependency, but maybe we should simply record the dependency as a string or JSON blob and not actually tie it to a derivation?

**Comment by adnelson** [comment] 2018-02-19 19:15
This would of course require changing how the resolution logic works, as well as `buildNodePackages`.

**Comment by ixmatus** [comment] 2018-02-19 20:07
Or, perhaps the solution is instead to make sure that packages listing another package as a peer dep are found by `circularClosure`.

I actually think the way that this has been built is correct and there's just a bug to deal with, which is that the uglify webpack plugin doesn't have `webpack` in its circular dependencies list. Which means it will never be found when `circularClosure` is run on `webpack`.

**Comment by ixmatus** [comment] 2018-02-19 20:08
Here is some useful information from `package.json` documentation:

> NOTE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. In the next major version of npm (npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead. 

https://docs.npmjs.com/files/package.json#peerdependencies

**Comment by adnelson** [comment] 2018-02-19 20:10
Ah, interesting. Well, maybe we can just ignore them then and let the warning/error logic handle things (since the default NPM version now uses npm3). This could potentially break existing packages though.

**Comment by ixmatus** [comment] 2018-02-19 20:12
IOW, I think it is _correct_ that we have detected a circular dependency. I just think we need to fix whatever issue is causing Package B to not include Package A in its own circularDependencies list even though it is in its peerDependencies list... You understand the circular dependencies solution better than I do, so what is your intuition on that?

**Comment by adnelson** [comment] 2018-02-19 20:14
Well, what I was thinking is that we can just not attempt to resolve peer dependencies at all. Just leave them as-is, and depend on the user to satisfy them if their packages need them. Basically removing [this line](https://github.com/adnelson/nixfromnpm/blob/d3cfd4adfd3e5b58ed65bc3688adf24ea2b4f116/src/NixFromNpm/Npm/Resolve.hs#L681) and the related code.

**Comment by adnelson** [comment] 2018-02-19 20:16
Also either remove or change handling of peer dependencies in `buildNodePackage` (e.g [this](https://github.com/adnelson/nixfromnpm/blob/d3cfd4adfd3e5b58ed65bc3688adf24ea2b4f116/nix-libs/nodeLib/buildNodePackage.nix#L344))

**Comment by ixmatus** [comment] 2018-02-19 20:17
Oh...I see what you're saying because peer dependencies are really just expressing an ambient environment constraint. Which, technically, we don't have this problem since we're building with Nix and can isolate package sets really easily.

Yes. I like your suggestion.

**Comment by adnelson** [comment] 2018-02-19 20:18
Cool. Do you want to tackle it or should I?

**Comment by ixmatus** [comment] 2018-02-19 20:19
I think you should, this was your suggested fix! I'm around to review.

**Comment by adnelson** [comment] 2018-02-22 21:27
Fixed by #112

**Closed by adnelson** 2018-02-22 21:27 UTC
