### ISSUE TITLE
Failed to parse

### ISSUE THREAD

**Issue by ollieh** [adnelson/nixfromnpm#66] opened 2016-08-03 16:36 UTC
Sorry to be such a bother! I get the following error:
```
$ nixfromnpm -f package.json -o ~/Projects/nix-node-packages --dev-depth 1 -r http://mycustomregistry/

. . . .

Warning: expression for fs-access version 1.0.0 failed to parse:
<string>:10:11: error: expected: "]",
    ., bool, identifier, integer,
    letter, list, null, parens,
    path, set, spath, string
      null-check_1-0-0 
          ^
```
fs-access/1.0.0.nix
```
{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "fs-access";
    version = "1.0.0";
    src = pkgs.fetchurl {
      url = "http://mycustomregistry/fs-access/-/fs-access-1.0.0.tgz";
      sha1 = "e96872b1f415ae302bdda4ef05309eb4bde1934c";
    };
    deps = with nodePackages; [
      null-check_1-0-0
    ];
    meta = {
      homepage = "https://github.com/sindresorhus/fs-access";
      description = "Node.js 0.12 fs.access() & fs.accessSync() ponyfill";
      keywords = [
        "built-in"
        "core"
        "ponyfill"
        "polyfill"
        "shim"
        "fs"
        "access"
        "stat"
        "mode"
        "permission"
        "user"
        "process"
        "check"
      ];
    };
  }
```
null-check/1.0.0.nix
```
{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "null-check";
    version = "1.0.0";
    src = pkgs.fetchurl {
      url = "http://mycustomregistry/null-check/-/null-check-1.0.0.tgz";
      sha1 = "977dffd7176012b9ec30d2a39db5cf72a0439edd";
    };
    deps = [];
    meta = {
      homepage = "https://github.com/sindresorhus/null-check";
      description = "Ensure a path doesn't contain null bytes";
      keywords = [
        "built-in"
        "core"
        "ponyfill"
        "polyfill"
        "shim"
        "fs"
        "path"
        "null"
        "bytes"
        "check"
      ];
    };
  }
```

Any idea what could be causing this? It looked to me like something to do with the hyphen, but there are plenty of other packages with hyphens in the name.

**Comment by ollieh** [comment] 2016-08-03 16:49
On second thought, could it be parsing `null` in `null-check` as the nix `null` value? I guess this is to do with hnix?

**Comment by ollieh** [comment] 2016-08-03 16:53
Changed the folder null-check to n-check, and the reference to it in fs-access/*.nix and default.nix, and it fixed it. I guess it's parsing it as null.

**Comment by adnelson** [comment] 2016-08-03 17:28
Yeah, looks like it's parsing it as `null - check_1-0-0`. This is indeed an hnix thing. Good catch. I think I ran into a similar thing with "assert" a while back which I fixed in hnix but apparently it didn't catch this one

**Comment by adnelson** [comment] 2016-08-03 17:33
On second thought it's not exactly an hnix thing, because if it's an invalid variable identifier there's not much that hnix can do about that. `nixfromnpm` itself could generate an expression that put things in quotes, for example instead of

```nix
with nodePackages; [ null-check_1-0-0 ]
```

it could generate

```nix
[ nodePackages."null-check_1-0-0" ]
```

**Comment by adnelson** [comment] 2016-08-03 17:38
oh derp, never mind this is an hnix thing. It's not that nix is failing to parse this, it's that hnix is failing to parse it. I'll try to fix the fixturized version of hnix that I have

**Comment by adnelson** [comment] 2016-08-03 18:10
@ollieh 

OK, I patched hnix to fix the parsing bug. I confirmed it worked by generating an expression `fs-access` and seeing that it works. (I also pushed fs-access to `nix-node-packages` master).

And no need to apologize for creating these issues, it's good to fix them :)

**Closed by adnelson** 2016-08-03 18:10 UTC
